const base = 'https://btx2-eus.github.io/historia-btx2/';
const files = {
  start: 'materialak/00_HASI_HEMEN.pdf', guide: 'materialak/01_IRAKASLEAREN_GIDA.pdf', dossier: 'materialak/02_IKASLEAREN_DOSIERRA.pdf', sources: 'materialak/03_ITURRIAK_ETA_JATORRIA.pdf', slidesGuide: 'materialak/06_AURKEZPENAREN_IBILBIDEA.pdf',
  notes: 'https://drive.google.com/file/d/1hQm7TSGGXW1gXcLyp64r8VlQ_J9whmMJ/view', slides: 'https://drive.google.com/file/d/11dwkpB42GfPNm4ExL37fqqVbS_Vvg0uN/view',
  theme: base + 'temas/01-antzinako-erregimena.html', chronology: base + 'kronologia.html', sourceGuide: base + 'iturriak-iruzkindu.html', trainerA: base + 'kontzeptu-entrenamendua.html', trainerB: base + 'iruzkin-entrenamendua.html'
};
const sessions = [
  {title:'Harrera: zer dago jokoan?', focus:'Boterearen zilegitasuna, herritartasuna eta lurralde-antolaketa; azken enkargua hasieratik argi.', steps:[['0–8','Hiru aztarna proiektatu: Goya, 1812ko subiranotasuna eta 1839ko foruak. Ikasleak lehen hipotesia idatzi; bikotean 2 minutu.'],['8–20','Irakasleak 1808→1812→1839→1868→1876 arkua, lau epigrafeak eta azken produktua aurkeztu.'],['20–35','Banakako diagnostikoa: kronologia, kontzeptuak eta 1812ko 3. artikulua. Ez jaso zuzentzeko.'],['35–45','Erantzunak ahoz/arbelean kontrastatu; ikasleak beste kolorez zuzendu.'],['45–50','Itxiera: «ulertu behar dut… / idazteko gai izan behar dut…».']], trace:'Hasierako hipotesia, diagnostiko autozuzendua eta produktuaren irizpideak.', check:'Ez da notarik; irakasleak bi hutsune ohiko hautematen ditu.', links:['start','dossier','sources','slidesGuide']},
  {title:'Independentzia Gerra eta Jose I.a', focus:'1808ko krisiaren kausak, Jose I.aren gobernua, frantsestuak eta juntak.', steps:[['0–5','Fontainebleau→Aranjuez→Maiatzaren 2a→Baionako abdikazioak→Bailén: kausa-lotura bat.'],['5–32','Irakaslearen azalpena apunteekin eta aurkezpeneko 16–24 diapositibekin.'],['32–38','Baionako Estatutuaren B1 eredua: testuko froga eta kanpoko jakintza bereizi.'],['38–47','F1 iturriari B1–B2 erantzun laburrak bakarka; kontraste gidatua.'],['47–50','Itxiera: Goyaren irudiak zer froga dezake eta zer ez?']], trace:'Kausa→eragile/erabaki→ondorio eskema eta F1eko bi erantzun.', check:'Lehen saiakera, gero autozuzenketa; ez bildu.', links:['notes','slides','dossier','sources','theme']},
  {title:'Cadiz eta 1812ko Konstituzioa', focus:'Subiranotasun nazionala, Gorteen erreformak, ordezkaritza eta herritartasunaren mugak.', steps:[['0–5','Juntak, Junta Zentrala eta Gorteen deialdia: 1808rekiko bi lotura.'],['5–28','Irakasleak 28–33 diapositibak azaltzen ditu; ikasleak zazpi galderako antolatzailea osatu.'],['28–34','1812ko Konstituzioan B1/B2 eredua: artikulua eta berehalako testuingurua.'],['34–45','F2 iturriaren B1–B3 bakarka eta gida erabiliz zuzendu.'],['45–50','«Herritartasuna zabaldu zuen… baina…»: emakumeen bazterketa ere zehaztu.']], trace:'Zazpi erantzun zehatz eta F2ren iruzkin laburra.', check:'Testuko froga markatuta; irakasleak akats kolektibo bat argitzen du.', links:['notes','slides','dossier','sources','sourceGuide']},
  {title:'1814–1868ko zubi historikoa', focus:'Estatu liberala ez zen amaituta jaio: absolutismoa, liberalismoa, administrazioa, jabetza eta parte-hartzea.', steps:[['0–5','1812, 1814, 1820, 1833, 1837, 1845, 1868: bi haustura.'],['5–33','Irakasleak lau eraikuntza-geruzak azaltzen ditu; 36–38, 42–45, 47 eta 49–50 diapositibak.'],['33–45','F3: 1812/1837/1845/1869 testuak alderatu; bi aldaketa eta jarraitutasun bat.'],['45–50','Giltza ahoz; ikasleak froga bat bikotekidearekin egiaztatu.']], trace:'Lau geruzako eskema eta hiru konparazio frogatu.', check:'Ez da epigrafe ofizial berria; 1.3 eta 1.4 ulertzeko testuingurua da.', links:['notes','slides','dossier','sources','chronology']},
  {title:'Seiurteko demokratikoa', focus:'1868ko haustura, 1869ko Konstituzioa, Amadeo, Lehen Errepublika eta ezegonkortasunaren arrazoiak.', steps:[['0–5','Isabel II.aren erorketa: kausa politiko bat eta ekonomiko/sozial bat.'],['5–30','Irakaslearen azalpena; 52–55, 57–58 eta 60–61 diapositibak.'],['30–36','C ataleko plan eredua: tesia, hiru etapa, balantzea.'],['36–47','Paragrafo kausala banaka idatzi; lau irizpideko autokontrastea.'],['47–50','Bi esaldi hobetu entzun; irakasleak kausa-aditz zehatza nabarmendu.']], trace:'C ataleko eskema eta paragrafo kausala.', check:'Ez da idazlan osoa jasotzen; ikasleak bere paragrafoa zuzentzen du.', links:['notes','slides','dossier','theme']},
  {title:'Foru-auzia I: karlismoa eta 1839', focus:'Foruak, karlismoa, Bergarako Hitzarmena eta 1839ko legearen bi klausulak.', steps:[['0–5','Foruak, karlismoa eta liberalismoa hiru esalditan bereizi.'],['5–31','Irakasleak Lehen Karlistaldia eta 1839ko ondorioak azaldu; 39–40 eta 65–69 diapositibak.'],['31–37','«Berresten dira» / «batasun konstituzionalari kalterik egin gabe» elkarrekin irakurri.'],['37–47','F4ri B1–B3 laburrak; lehen erantzuna eta zuzenketa bereizi.'],['47–50','IA baimendua bada, etxerako feedback-protokoloa azaldu; bestela paperezko gida.']], trace:'Kausa→gatazka→konponbide→muga eta F4ko erantzunak.', check:'IAren iradokizuna ez da froga; apunte eta iturrian egiaztatu.', links:['notes','slides','dossier','sources','trainerB']},
  {title:'Foru-auzia II: 1876 eta 1878', focus:'Foru-erregimenaren erreforma, betebehar militarrak/fiskalak eta Kontzertu Ekonomikoaren hasiera.', steps:[['0–5','1833–1878ko bost mugarri ordenatu.'],['5–24','Irakaslearen azalpena; 70–72 diapositibak eta 1878ko bereizketa.'],['24–39','F4 eta F5 alderatu: tesi laburra eta bi testu-froga.'],['39–43','Alboko bikotearekin objekzio historiko bat trukatu.'],['43–50','Autokontrastea, PAUrako zalantza eta ikasketa-ekintza.']], trace:'1839/1876 konparazioa, jarraitutasuna eta haustura.', check:'«Abolizioa» hitza ez da azalpen osoa; testuak dioena eta ondorioa bereizi.', links:['notes','slides','dossier','sources','chronology']},
  {title:'PAU klinika: lehen saiakera eta berridazketa', focus:'A1eko kontzeptuen erlazio historikoa denborapean, ondoren feedback egiaztatua.', steps:[['0–5','Sei kontzeptu, 90–130 hitz; lau hautatu eta azpimarratu, biren arteko lotura historiko esplizitua planifikatu.'],['5–20','A1 lehen bertsioa bakarka, kronometratuta eta laguntzarik gabe.'],['20–24','Bikotekideak froga duen ohar bakarra egiten du.'],['24–36','Webeko entrenatzailea edo egiaztapen-gida; gehienez hiru hobekuntza egiaztatu.'],['36–43','Akats kolektibo anonimoa; 2–3 esaldi berridatzi.'],['43–50','M9ko tesia, bost mugarri eta bi iturri planifikatu.']], trace:'A1en lehen bertsioa, egiaztapena eta berridazketa.', check:'Tresnak laguntzen du, baina ez du erantzuna idazten; lehen bertsioa gorde.', links:['dossier','trainerA','theme','notes']},
  {title:'Azken produktua eta itxiera', focus:'250–300 hitzeko ohar kuratorial historikoa: tesi arrazoitua, bost mugarri eta bi iturri.', steps:[['0–5','Enkargua eta lau adierazleko errubrika gogorarazi; eredua ez erakutsi.'],['5–35','Banakako idazketa isila, dosierraren planarekin.'],['35–42','Autoebaluazioa: 0–8 puntu, testuan markatutako frogarekin; esaldi bat zuzendu.'],['42–45','Bikotean objekzio historiko bakarra; behar bada inferentzia hobetu.'],['45–50','«Lehen uste nuen… / orain azal dezaket… / berrikusiko dut…».']], trace:'Ohar kuratorial historikoa eta autoebaluazio arrazoitua.', check:'Produktu ebaluagarria, baina ez irakasleak zuzendutako beste kalifikazio bat.', links:['dossier','sources','chronology','theme']}
];
const labels={start:'Hasi hemen',guide:'Irakaslearen gida',dossier:'Ikaslearen dosierra',sources:'Iturriak F0–F5',slidesGuide:'Diapositiben ibilbidea',notes:'Unikopia apunteak · Drive',slides:'Aurkezpen nagusia · Drive',theme:'Ikasleen webeko 1. gaia',chronology:'Kronologia',sourceGuide:'Iturri-iruzkinaren gida',trainerA:'A1 entrenatzailea',trainerB:'B entrenatzailea'};
const resources=[['start','Abiapuntua','Saioen mapa, benetako muga eta prestaketa.'],['guide','Irakaslearen gida','Bederatzi saioak minutuz minutu.'],['dossier','Ikaslearen dosierra','Ariketak, idazketa, azken produktua eta autoebaluazioa.'],['sources','Iturriak eta jatorria','F0–F5; testu-zatiak eta jatorri-estekak.'],['slidesGuide','Aurkezpenaren ibilbidea','74 diapositibetatik saio bakoitzerako hautaketa.'],['notes','Unikopia apunteak','Ezagutza-oinarria; 1. gaia, PDFko 3–15. orrialdeak. Baimena behar da.'],['slides','Aurkezpen nagusia','Jatorrizko PowerPointa, Driveko baimenarekin.'],['theme','Ikasleen weba: 1. gaia','Eduki eta ikasketa digitalerako osagarria.'],['chronology','Kronologia','Prozesuak denboran kokatzeko.'],['sourceGuide','Iturrien gida','B ataleko iruzkina lantzeko.'],['trainerA','A1 entrenatzailea','Lehen saiakeraren ondoko feedbacka.'],['trainerB','B entrenatzailea','Iturri-iruzkinen feedbacka.']];
let themes=[];let selectedTheme=1;let selectedSession=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function link(key){const href=files[key], external=href.startsWith('http');return `<a href="${esc(href)}" ${external?'target="_blank" rel="noopener"':''}>${esc(labels[key])}${external?' ↗':' ↓'}</a>`}
function renderResources(){document.querySelector('#resource-grid').innerHTML=resources.map(([key,title,desc])=>`<article class="resource"><h4>${esc(title)}</h4><p>${esc(desc)}</p>${link(key)}</article>`).join('')}
function renderSession(){const s=sessions[selectedSession];document.querySelector('#session-nav').innerHTML=sessions.map((_,i)=>`<button type="button" data-session="${i}" class="${i===selectedSession?'active':''}" aria-label="${i+1}. saioa" aria-pressed="${i===selectedSession}">${i+1}. saioa</button>`).join('');document.querySelector('#session-card').innerHTML=`<p class="session-kicker">${selectedSession+1}. SAIOA · 50 MINUTU</p><h3>${esc(s.title)}</h3><p class="session-summary">${esc(s.focus)}</p><h4>Gelako sekuentzia</h4><div class="timeline">${s.steps.map(([time,activity])=>`<div class="time-row"><b>${esc(time)}</b><span>${esc(activity)}</span></div>`).join('')}</div><div class="session-bottom"><div><h4>Ikaslearen aztarna</h4><p>${esc(s.trace)}</p></div><div><h4>Zuzenketa bideragarria</h4><p>${esc(s.check)}</p></div></div><div class="session-links">${s.links.map(link).join('')}</div>`;document.querySelectorAll('[data-session]').forEach(b=>b.addEventListener('click',()=>{selectedSession=Number(b.dataset.session);renderSession()}))}
function renderTheme(){const t=themes.find(x=>x.number===selectedTheme);if(!t)return;document.querySelector('#theme-list').innerHTML=themes.map(x=>`<button class="theme-button ${x.number===selectedTheme?'selected':''}" type="button" data-theme="${x.number}" aria-current="${x.number===selectedTheme?'page':'false'}"><span class="theme-number">${x.number}</span><span class="theme-text">${esc(x.title)}<span class="theme-state">${x.status==='osatua'?'M1 · materialak prest':'Gaitegia · materialak planifikatzeke'}</span></span></button>`).join('');document.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>{selectedTheme=Number(b.dataset.theme);renderTheme()}));const main=document.querySelector('.main-panel');if(selectedTheme===1){main.innerHTML=window.firstPanel;renderSession();renderResources();bindTabs();return}main.innerHTML=`<div class="section-label"><span class="pill future">${selectedTheme}. GAIA · GAITEGIA</span><span>2026–27ko izendegi ofiziala</span></div><h2>${selectedTheme}. GAIA. ${esc(t.title)}</h2><div class="epigraph-box"><h3>USaP/PAUko epigrafe ofizialak</h3><ol>${t.epigraphs.map(e=>`<li>${esc(e.code)} ${esc(e.title)}</li>`).join('')}</ol></div><div class="future-panel"><h3>Oraindik ez dago irakasteko sekuentzia osorik</h3><p>Gai honen izenburu eta epigrafeak egiaztatuta daude; saioak, materialak, ebaluazio-arrastoak eta NCA/LOMLOE lotura zehatza oraindik prestatu behar dira. Ez erabili M1eko materialak gai honen ordezko gisa.</p></div>`}
function bindTabs(){document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>{t.classList.toggle('active',t===tab);t.setAttribute('aria-selected',String(t===tab))});document.querySelectorAll('.panel').forEach(p=>{const active=p.id===tab.dataset.panel;p.classList.toggle('active',active);p.hidden=!active})}))}
window.firstPanel=document.querySelector('.main-panel').innerHTML;
fetch('gaitegia.json').then(r=>{if(!r.ok)throw Error('Gaitegia ezin izan da kargatu');return r.json()}).then(data=>{themes=data;renderTheme()}).catch(()=>{document.querySelector('#theme-list').innerHTML='<p>Gaitegia ezin izan da kargatu. Saiatu berriro orria freskatzen.</p>';renderSession();renderResources();bindTabs()});
